---
apiVersion: jvmbuildservice.io/v1alpha1
kind: JBSConfig
metadata:
  name: jvm-build-config
  annotations:
    jvmbuildservice.io/s3-bucket-name: "jvm-build-service-data"
spec:
  registry:
    owner: QUAY_USERNAME
  cacheSettings:
    storage:  "60Gi"
  mavenDeployment:
    username: MAVEN_USERNAME
    repository: MAVEN_REPOSITORY
  gitDeployment:
    identity: GIT_DEPLOY_IDENTITY
    url: GIT_DEPLOY_URL
  relocationPatterns:
    - relocationPattern:
        buildPolicy: "default"
        patterns:
          - pattern:
              from: (io.github.stuartwdouglas.hacbs-test.simple):(simple-jdk17):(99-does-not-exist)
              to: io.github.stuartwdouglas.hacbs-test.simple:simple-jdk17:0.1.2
