---
apiVersion: jvmbuildservice.io/v1alpha1
kind: UserConfig
metadata:
  name: jvm-build-config
spec:
  enableRebuilds: true
  mavenBaseLocations:
    maven-repository-300-jboss: "https://repository.jboss.org/nexus/content/groups/public/"
    maven-repository-301-jitpack: "https://jitpack.io"
    maven-repository-302-confluent: "https://packages.confluent.io/maven"
    maven-repository-303-gradle: "https://repo.gradle.org/artifactory/libs-releases"
    maven-repository-304-eclipselink: "https://download.eclipse.org/rt/eclipselink/maven.repo"
    maven-repository-305-redhat: "https://maven.repository.redhat.com/ga"
    maven-repository-306-gradleplugins: "https://plugins.gradle.org/m2"
    maven-repository-307-jsweet: "https://repository.jsweet.org/artifactory/libs-release-local"
    maven-repository-308-jenkins: "https://repo.jenkins-ci.org/public/"

