apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/tektoncd/pipeline/releases/download/v0.34.1/release.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.5/git-clone.yaml
  - maven-v0.2.yaml
  - lookup-artifact-location-v0.1.yaml
  - run-maven-component-build-v0.1.yaml
  - run-gradle-component-build-v0.1.yaml
