apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hacbs-jvm-operator
resources:
  - deployment.yaml
  - sa.yaml
  - namespace.yaml
  - rbac.yaml
  - metricservice.yaml
  - servicemonitor.yaml
  - servicemonitor_rbac.yaml
