apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jvmbuildservice.io_dependencybuilds.yaml
  - jvmbuildservice.io_artifactbuilds.yaml
  - jvmbuildservice.io_rebuiltartifacts.yaml
  - jvmbuildservice.io_systemconfigs.yaml
  - jvmbuildservice.io_userconfigs.yaml
