#TODO  long term, do we want to merge this with <repoHome>/deploy/base/config.yaml ??
---
apiVersion: jvmbuildservice.io/v1alpha1
kind: UserConfig
metadata:
  name: jvm-build-config
spec:
  enableRebuilds: true
  mavenBaseLocations:
    maven-repository-300-jboss: "https://repository.jboss.org/nexus/content/groups/public/"
    maven-repository-301-jitpack: "https://jitpack.io"
    maven-repository-302-confluent: "https://packages.confluent.io/maven"
    maven-repository-303-gradle: "https://repo.gradle.org/artifactory/libs-releases"
    maven-repository-304-eclipselink: "https://download.eclipse.org/rt/eclipselink/maven.repo"
    maven-repository-305-redhat: "https://maven.repository.redhat.com/ga"
    maven-repository-306-gradleplugins: "https://plugins.gradle.org/m2"
    maven-repository-307-jsweet: "https://repository.jsweet.org/artifactory/libs-release-local"
    maven-repository-308-jenkins: "https://repo.jenkins-ci.org/public/"
    maven-repository-309-spring-plugins: "https://repo.springsource.org/plugins-release"
    maven-repository-309-spring-plugins: https://repo.springsource.org/plugins-release
    maven-repository-310-dokkadev: https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev
    maven-repository-311-ajoberstar: https://ajoberstar.org/bintray-backup
    maven-repository-312-googleandroid: https://dl.google.com/dl/android/maven2/
    maven-repository-313-kotlinnative14linux: https://download.jetbrains.com/kotlin/native/builds/releases/1.4/linux
    maven-repository-314-jcs: https://packages.jetbrains.team/maven/p/jcs/maven
  owner: {{ .Values.quayTestRepoOwner }}
  prependTag: "{{ .Values.prependTag }}"
  relocationPatterns:
  - relocationPattern:
      buildPolicy: default
      patterns:
      - pattern:
          from: (io.github.stuartwdouglas.hacbs-test.simple):(simple-jdk17):(99-does-not-exist)
          to: io.github.stuartwdouglas.hacbs-test.simple:simple-jdk17:0.1.2
  repository: test-images

