apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- servicemonitor.yaml
- servicemonitor_rbac.yaml
- ../../base


images:
- name: hacbs-jvm-operator
  newName: jvm-build-service-image
  newTag: dev


patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
  target:
    kind: Deployment
    name: hacbs-jvm-operator
- patch: |-
    - op: add
      path: /metadata/labels
      value: {openshift.io/cluster-monitoring: "true"}
  target:
    kind: Namespace
    name: jvm-build-service
